<!DOCTYPE html>
<html>
	<section>



			        <!-- messages:-->
	    <div class="messageE">
	       
             <?php         
         
             if(empty($_SESSION['messageSA'])==false)
             	echo '<p >'.$_SESSION['messageSA'].'</p>'; 

	             $_SESSION['messageSA']=null; 
	        
	                     
             ?>

        </div>
	<!-- On cherche nos annonces-->	

		<div >
			<?php if (empty($annoncePs)!==true):?>
				<table class="table1">
     <!-- On compte combien on a des annonces-->				
					<?php 
						$counter=0; 
						foreach ($annoncePs as $key)
						$counter+=1; 
					    if($counter==1|$counter==0)
						    	$message=$counter.' chat perdu'; 
						else
						    	$message=$counter.' chats perdus';
			        ?>
			        <?php if($counter>=0):?>	       
			        	<caption>Nous avons <?=$message?> </caption>
			        <?php endif;?>	  	
					<tbody>

						<?php foreach($annoncePs as $key =>$annonce): ?>

							<tr >
								<?php 
									if($annonce['sex']=='femelle')
									{
										$sex='chatte';
										$type='perdue';  
									}
									else
									{
										$sex='chat';
										$type='perdu'; 
									}
								?>

								<td class="block"><img src=<?=$annonce['url']?> style="width:125px; height: 125px;" title='<?=$annonce['name'].', '.$sex.' '.$type.' le ' .$annonce['datePT'] ?>'></td>


								<td class="block">
									<p><?=$annonce['name'].', '.$sex.' <span style="color:red">'.$type.'</span> le '.$annonce['datePT']?></p>
									<p><?='<strong>Lieu :</strong>'.$annonce['rue'].' '.$annonce['arrondissement'].' Marseille'?></p>
								</td>
								
								<td >
								   
									<a href='detailA.php?idchat=<?=$annonce['idchat']?>&type=perdu'>Le détail » 
									</a>
								</td>
							</tr>

                        <?php  endforeach;?>
					</tbody>
				</table>
			<?php endif;?>
		</div>

	</section>
</html>