<!DOCTYPE html>
<html>
		<section>
			<?php if (empty($annoncePs)!==true):?>
				<table class="table1">
					<caption>Les chats perdus</caption>	
					<tbody>

						<?php foreach($annoncePs as $key =>$annonce): ?>

							<tr>
								<?php 
									if($annonce['sex']=='femelle')
									{
										$sex='chatte';
										$type='perdue';  
									}
									else
									{
										$sex='chat';
										$type='perdu'; 
									}
								?>

								<td><img src=<?=$annonce['url']?> style="width:100px; height: 100px;" title='<?=$annonce['name'].', '.$sex.' '.$type.' le ' .$annonce['datePT'] ?>'></td>


								<td>
									<p><?=$annonce['name'].', '.$sex.' <span style="color:red">'.$type.'</span> le '.$annonce['datePT']?></p>
									<p><?='Lieu :  '.$annonce['rue'].' '.$annonce['arrondissement'].' Marseille'?></p>
								</td>
								
								<td>
									<a href="detail.php?idchat=<?=$annonce['idchat']?>&type=perdu">
										 Le détail » 
									</a>
								</td>
							</tr>

                        <?php  endforeach;?>
					</tbody>
				</table>
			<?php endif;?>

			<?php if (empty($annonceTs)!==true):?>
				<table class="table2">
					<caption>Les chats trouvés</caption>	
					<tbody>

						<?php foreach($annonceTs as $key =>$annonce): ?>

							<tr>
								<?php 
									if($annonce['sex']=='femelle')
									{
										$sex='chatte';
										$type='trouvée';
									} 
									else
									{
										$sex='chat';
										$type='trouvé'; 
									}
								?>

								<td><img src=<?=$annonce['url']?> style="width:100px; height: 100px;" title='<?=$annonce['name'].', '.$sex.' '. $type.' le '.$annonce['datePT'] ?>'></td>


								<td>
									<p><?=$annonce['name'].', '.$sex.' <span style="color:rgb(12, 155, 160);"> '.$type.'</span> le '.$annonce['datePT']?></p>
									<p><?='Lieu :  '.$annonce['rue'].' '.$annonce['arrondissement'].' Marseille'?></p>
								</td>
								
								<td>
									<a href="detail.php?idchat=<?=$annonce['idchat']?>&type=trouve">
										 Le détail » 
									</a>
								</td>
							</tr>
							
                        <?php  endforeach;?>
					</tbody>
				</table>
			<?php endif;?>
			<?php if (empty($annonceRTs)!==true):?> 
				<table class="table3">
					<caption>Les chats retrouvés</caption>	
					<tbody>

						<?php foreach($annonceRTs as $key =>$annonce): ?>

							<tr>
								<?php 
									if($annonce['sex']=='femelle')
									{
										$sex='chatte'; 
										$type='retrouvée'; 
									}
									else
									{
										$sex='chat';
										$type='retrouvé'; 
									}
								?>

								<td><img src=<?=$annonce['url']?> style="width:100px; height: 100px;" title='<?=$annonce['name'].', '.$sex.' '.$type  ?>'></td>


								<td>

									<?php 
									$dateModifier=$annonce['dateModifier'];
									$dateRT=date("d/m/Y", strtotime($dateModifier)); ?>
									<p><?=$annonce['name'].', '.$sex.' <span style="color:green;"> '.$type.'</span> le '.$dateRT?></p>
									<p><?='Lieu :  '.$annonce['rue'].' '.$annonce['arrondissement'].' Marseille'?></p>
								</td>
								
								<td>
									<img src="img/0782440117.png" style="width:75px; height: 75px;">
								</td>
							</tr>
							
                        <?php  endforeach;?>
					</tbody>
				</table>
			<?php endif;?>				

		</section>
	</section>

	<!--L'endroit de publicité -->		
	<div class="publicite" id="p1">
			<h3>publicité</h3>
			<a href="<?=$publiciteDetail1[0]['lien']?>" ><img src="<?=$publiciteDetail1[0]['url']?>"></a>
	</div>
   	<?php if($publiciteDetail1[0]['url']=='null'):?>

			<script >		
		     document.getElementById("p1").style.display = "none";	
			</script>
			
		<?php endif;?>	
		

</html>
