<!DOCTYPE html>
<html>
	<section>
			        <!-- messages:-->
	    <div class="messageE">
	       
             <?php         
         
             if(empty($_SESSION['messageSA'])==false)
             	echo '<p >'.$_SESSION['messageSA'].'</p>'; 

	             $_SESSION['messageSA']=null; 
	        
	                     
             ?>

	    </div>
	<!-- On cherche nos annonces-->	

		<div>
			<?php if (empty($annonceRTs)!==true):?>
				<table class="table3">
     <!-- On compte combien on a des annonces-->				
					<?php 
						$counter=0; 
						foreach ($annonceRTs as $key)
						$counter+=1; 
					    if($counter==1|$counter==0)
						    	$message=$counter.' chat retrouvé'; 
						else
						    	$message=$counter.' chats retrouvés';
			        ?>
			        <?php if($counter>=0):?>	       
			        	<caption><?=$message?> </caption>
			        <?php endif;?>			           
					<tbody>

						<?php foreach($annonceRTs as $key =>$annonce): ?>
                            
							<tr>
								<?php 
									if($annonce['sex']=='femelle')
									{
										$sex='chatte'; 
										$type='retrouvée'; 
									}
									else
									{
										$sex='chat';
										$type='retrouvé'; 
									}
								?>

								<td class="block"><img src=<?=$annonce['url']?> style="width:125px; height: 125px;" title='<?=$annonce['name'].', '.$sex.' '.$type  ?>'></td>


								<td class="block">

									<?php 
									$dateModifier=$annonce['dateModifier'];
									$dateRT=date("d/m/Y", strtotime($dateModifier)); ?>
									<p><?=$annonce['name'].', '.$sex.' <span style="color:blue;"> '.$type.'</span> le '.$dateRT?></p>
									<p><?='<strong>Lieu :</strong>  '.$annonce['rue'].' '.$annonce['arrondissement'].' Marseille'?></p>
								</td>
								
								<td>
								    <a href="#" onclick="confirmation(<?=$annonce['idchat']?>)" >Supprimer</a>
								   
								</td>
							</tr>

                        <?php  endforeach;?>
					</tbody>
				</table>
			<?php endif;?>	
		</div>

    
	</section>

	

</html>
   <script type="text/javascript">
   	 function confirmation( id )
   	 	 {
        
			if (confirm("Voulez-vous vraiment supprimer cette annonce ?" ))
				 {
					window.location.href = "supprimerA.php?id="+id+"&type=<?=$annonce['type']?>"; 
				 }
		}
   </script>  
